language: python

python: 
    - "3.6"

install: pip install -r requirements.txt

before_script:
  - python -m spacy download en_core_web_sm

script:
  - python manage.py test
  - coverage erase
  - python manage.py cov

after_success:
  - codecov
